version: "3"
services:

  demo-rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: 'rabbitmq'
      RABBITMQ_DEFAULT_PASS: 'rabbitmq'
    networks:
      - demo-network
  
  demo-zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - demo-network

  demo-kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 'localhost'
      KAFKA_CREATE_TOPICS: "demo-topic:1:1" # topic:partition:replicas
      KAFKA_ZOOKEEPER_CONNECT: demo-zookeeper:2181
    depends_on:
      - demo-zookeeper
    links:
      - demo-zookeeper
    networks:
      - demo-network

  demo-kafka-manager:
    image: sheepkiller/kafka-manager:latest
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: demo-zookeeper:2181
      APPLICATION_SECRET: letmein
      KM_ARGS: -Djava.net.preferIPv4Stack=true
    links:
      - demo-zookeeper
      - demo-kafka
    networks:
      - demo-network

networks:
  demo-network:
    driver: bridge

volumes:
  demo-volumn: